/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package usersmovieratingsimilarity;

import javax.swing.JOptionPane;

/**
 *
 * @author Faisal Ahmed
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        String ItemNames[]={"No Comment","1","2","3","4","5"};
        
        
        Item1_1.removeAllItems();
        for(String str : ItemNames) {
         Item1_1.addItem(str);
        }
        Item1_2.removeAllItems();
        for(String str : ItemNames) {
         Item1_2.addItem(str);
        }
        Item1_3.removeAllItems();
        for(String str : ItemNames) {
         Item1_3.addItem(str);
        }
        Item1_4.removeAllItems();
        for(String str : ItemNames) {
         Item1_4.addItem(str);
        }
        
        
        Item2_1.removeAllItems();
        for(String str : ItemNames) {
         Item2_1.addItem(str);
        }
        Item2_2.removeAllItems();
        for(String str : ItemNames) {
         Item2_2.addItem(str);
        }
        Item2_3.removeAllItems();
        for(String str : ItemNames) {
         Item2_3.addItem(str);
        }
        Item2_4.removeAllItems();
        for(String str : ItemNames) {
         Item2_4.addItem(str);
        }
        
        
        Item3_1.removeAllItems();
        for(String str : ItemNames) {
         Item3_1.addItem(str);
        }
        Item3_2.removeAllItems();
        for(String str : ItemNames) {
         Item3_2.addItem(str);
        }
        Item3_3.removeAllItems();
        for(String str : ItemNames) {
         Item3_3.addItem(str);
        }
        Item3_4.removeAllItems();
        for(String str : ItemNames) {
         Item3_4.addItem(str);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Movie1 = new javax.swing.JLabel();
        Movie2 = new javax.swing.JLabel();
        Movie3 = new javax.swing.JLabel();
        Movie4 = new javax.swing.JLabel();
        User1 = new javax.swing.JLabel();
        User2 = new javax.swing.JLabel();
        User3 = new javax.swing.JLabel();
        Item1_1 = new javax.swing.JComboBox<>();
        Item1_2 = new javax.swing.JComboBox<>();
        Item1_3 = new javax.swing.JComboBox<>();
        Item1_4 = new javax.swing.JComboBox<>();
        Item2_1 = new javax.swing.JComboBox<>();
        Item2_2 = new javax.swing.JComboBox<>();
        Item2_3 = new javax.swing.JComboBox<>();
        Item2_4 = new javax.swing.JComboBox<>();
        Item3_1 = new javax.swing.JComboBox<>();
        Item3_2 = new javax.swing.JComboBox<>();
        Item3_3 = new javax.swing.JComboBox<>();
        Item3_4 = new javax.swing.JComboBox<>();
        GetSimilarity = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 0));
        setBounds(new java.awt.Rectangle(300, 160, 0, 0));

        Movie1.setBackground(new java.awt.Color(204, 255, 204));
        Movie1.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        Movie1.setText("Movie1");

        Movie2.setBackground(new java.awt.Color(204, 255, 204));
        Movie2.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        Movie2.setText("Movie2");

        Movie3.setBackground(new java.awt.Color(204, 255, 204));
        Movie3.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        Movie3.setText("Movie3");

        Movie4.setBackground(new java.awt.Color(204, 255, 204));
        Movie4.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        Movie4.setText("Movie4");

        User1.setBackground(new java.awt.Color(102, 153, 255));
        User1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        User1.setText("User1");

        User2.setBackground(new java.awt.Color(102, 153, 255));
        User2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        User2.setText("User2");

        User3.setBackground(new java.awt.Color(102, 153, 255));
        User3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        User3.setText("User3");

        Item1_1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Item1_2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Item1_3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Item1_4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Item2_1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Item2_2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Item2_3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Item2_4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Item3_1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Item3_2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Item3_3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Item3_4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        GetSimilarity.setText("GetSimilarity");
        GetSimilarity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetSimilarityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(GetSimilarity, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(User1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(User2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(User3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(17, 17, 17)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Movie1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(89, 89, 89)
                                .addComponent(Movie2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Item3_1, 0, 64, Short.MAX_VALUE)
                                    .addComponent(Item2_1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Item1_1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(87, 87, 87)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Item1_2, 0, 67, Short.MAX_VALUE)
                                    .addComponent(Item2_2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Item3_2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Item1_3, 0, 66, Short.MAX_VALUE)
                            .addComponent(Item2_3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Item3_3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Movie3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Item1_4, javax.swing.GroupLayout.Alignment.LEADING, 0, 76, Short.MAX_VALUE)
                            .addComponent(Item2_4, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Item3_4, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Movie4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(176, 176, 176))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Movie2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Movie3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Movie4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Movie1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(User1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Item1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Item1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Item1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Item1_4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(User2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Item2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Item2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Item2_3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Item2_4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(User3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Item3_1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Item3_2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Item3_3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Item3_4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(GetSimilarity, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GetSimilarityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetSimilarityActionPerformed

        // TODO add your handling code here:
        
        int i,j;
        int[][] mat = new int[5][5];
        
        mat[0][0]=Item1_1.getSelectedIndex();
        mat[0][1]=Item1_2.getSelectedIndex();
        mat[0][2]=Item1_3.getSelectedIndex();
        mat[0][3]=Item1_4.getSelectedIndex();
        
        mat[1][0]=Item2_1.getSelectedIndex();
        mat[1][1]=Item2_2.getSelectedIndex();
        mat[1][2]=Item2_3.getSelectedIndex();
        mat[1][3]=Item2_4.getSelectedIndex();
        
        mat[2][0]=Item3_1.getSelectedIndex();
        mat[2][1]=Item3_2.getSelectedIndex();
        mat[2][2]=Item3_3.getSelectedIndex();
        mat[2][3]=Item3_4.getSelectedIndex();
        
        SimilarityCalculation temp = new SimilarityCalculation();
        boolean res=temp.Calc(mat);
        if(res == true)
            JOptionPane.showMessageDialog(null,"User1 is more similar to User2 than User3");
        else
            JOptionPane.showMessageDialog(null,"User1 is more similar to User3 than User2");
        
    }//GEN-LAST:event_GetSimilarityActionPerformed

    /**
     * @param args the command line arguments
     */
    public void InterfaceCalling() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GetSimilarity;
    private javax.swing.JComboBox<String> Item1_1;
    private javax.swing.JComboBox<String> Item1_2;
    private javax.swing.JComboBox<String> Item1_3;
    private javax.swing.JComboBox<String> Item1_4;
    private javax.swing.JComboBox<String> Item2_1;
    private javax.swing.JComboBox<String> Item2_2;
    private javax.swing.JComboBox<String> Item2_3;
    private javax.swing.JComboBox<String> Item2_4;
    private javax.swing.JComboBox<String> Item3_1;
    private javax.swing.JComboBox<String> Item3_2;
    private javax.swing.JComboBox<String> Item3_3;
    private javax.swing.JComboBox<String> Item3_4;
    private javax.swing.JLabel Movie1;
    private javax.swing.JLabel Movie2;
    private javax.swing.JLabel Movie3;
    private javax.swing.JLabel Movie4;
    private javax.swing.JLabel User1;
    private javax.swing.JLabel User2;
    private javax.swing.JLabel User3;
    // End of variables declaration//GEN-END:variables
}
